name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type:bug", "status:triage"]
assignees:
  - xbreaker
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Don't forget to check for existing issues/discussions regarding your proposal. We might already have it.
        https://github.com/xbreaker/franz/issues
        https://github.com/xbreaker/franz/discussions
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        We'd like you to provide an example setup (via docker-compose, helm, etc.) 
        to reproduce the problem, especially with a complex setups.
      value: "Steps to reproduce the behavior:
      1. "
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. 
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
